
// This file has been generated by the GUI designer. Do not modify.
namespace PushLocal
{
	public partial class TestWindow
	{
		private global::Gtk.Notebook Pages;
		
		private global::Gtk.ScrolledWindow NotifyScrollbar;
		
		private global::Gtk.VBox notifyVBox;
		
		private global::PushLocal.NotificationWidget notificationwidget1;
		
		private global::PushLocal.NotificationWidget notificationwidget2;
		
		private global::PushLocal.NotificationWidget notificationwidget3;
		
		private global::Gtk.Label Notifications;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TextView NetworkTextArea;
		
		private global::Gtk.Label Network;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget PushLocal.TestWindow
			this.Name = "PushLocal.TestWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("TestWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child PushLocal.TestWindow.Gtk.Container+ContainerChild
			this.Pages = new global::Gtk.Notebook ();
			this.Pages.CanFocus = true;
			this.Pages.Name = "Pages";
			this.Pages.CurrentPage = 1;
			// Container child Pages.Gtk.Notebook+NotebookChild
			this.NotifyScrollbar = new global::Gtk.ScrolledWindow ();
			this.NotifyScrollbar.CanFocus = true;
			this.NotifyScrollbar.Name = "NotifyScrollbar";
			this.NotifyScrollbar.HscrollbarPolicy = ((global::Gtk.PolicyType)(2));
			this.NotifyScrollbar.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child NotifyScrollbar.Gtk.Container+ContainerChild
			global::Gtk.Viewport w1 = new global::Gtk.Viewport ();
			w1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.notifyVBox = new global::Gtk.VBox ();
			this.notifyVBox.Name = "notifyVBox";
			this.notifyVBox.Spacing = 6;
			// Container child notifyVBox.Gtk.Box+BoxChild
			this.notificationwidget1 = new global::PushLocal.NotificationWidget ();
			this.notificationwidget1.HeightRequest = 75;
			this.notificationwidget1.Events = ((global::Gdk.EventMask)(256));
			this.notificationwidget1.Name = "notificationwidget1";
			this.notifyVBox.Add (this.notificationwidget1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.notifyVBox [this.notificationwidget1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child notifyVBox.Gtk.Box+BoxChild
			this.notificationwidget2 = new global::PushLocal.NotificationWidget ();
			this.notificationwidget2.HeightRequest = 75;
			this.notificationwidget2.Events = ((global::Gdk.EventMask)(256));
			this.notificationwidget2.Name = "notificationwidget2";
			this.notifyVBox.Add (this.notificationwidget2);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.notifyVBox [this.notificationwidget2]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child notifyVBox.Gtk.Box+BoxChild
			this.notificationwidget3 = new global::PushLocal.NotificationWidget ();
			this.notificationwidget3.HeightRequest = 75;
			this.notificationwidget3.Events = ((global::Gdk.EventMask)(256));
			this.notificationwidget3.Name = "notificationwidget3";
			this.notifyVBox.Add (this.notificationwidget3);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.notifyVBox [this.notificationwidget3]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			w1.Add (this.notifyVBox);
			this.NotifyScrollbar.Add (w1);
			this.Pages.Add (this.NotifyScrollbar);
			// Notebook tab
			this.Notifications = new global::Gtk.Label ();
			this.Notifications.Name = "Notifications";
			this.Notifications.Xalign = 1F;
			this.Notifications.LabelProp = global::Mono.Unix.Catalog.GetString ("Notifications");
			this.Pages.SetTabLabel (this.NotifyScrollbar, this.Notifications);
			this.Notifications.ShowAll ();
			// Container child Pages.Gtk.Notebook+NotebookChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.NetworkTextArea = new global::Gtk.TextView ();
			this.NetworkTextArea.CanFocus = true;
			this.NetworkTextArea.Name = "NetworkTextArea";
			this.NetworkTextArea.Editable = false;
			this.NetworkTextArea.AcceptsTab = false;
			this.NetworkTextArea.WrapMode = ((global::Gtk.WrapMode)(2));
			this.GtkScrolledWindow.Add (this.NetworkTextArea);
			this.Pages.Add (this.GtkScrolledWindow);
			global::Gtk.Notebook.NotebookChild w9 = ((global::Gtk.Notebook.NotebookChild)(this.Pages [this.GtkScrolledWindow]));
			w9.Position = 1;
			// Notebook tab
			this.Network = new global::Gtk.Label ();
			this.Network.Name = "Network";
			this.Network.LabelProp = global::Mono.Unix.Catalog.GetString ("Network");
			this.Pages.SetTabLabel (this.GtkScrolledWindow, this.Network);
			this.Network.ShowAll ();
			this.Add (this.Pages);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 392;
			this.DefaultHeight = 300;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		}
	}
}
